### ISSUE TITLE
Add a link to this repository in the Footer component (github icon)

### ISSUE THREAD

**Issue by Abrosss** [Abrosss/devquiz-quiz-app#14]
![Screenshot_47](https://github.com/Abrosss/devquiz-quiz-app/assets/84074575/9da1bb41-607f-4342-80a8-d9d0e77a3039)

**Comment by jonichi16** [comment]
Kindly review my PR and let me know if you have any questions. Thank you :)

**Comment by Abrosss** [comment]
Hi @jonichi16 Thank you for adding the link and for your contribution!
