### ISSUE TITLE
Fix the small gap between divs in the Result component

### ISSUE THREAD

**Issue by Abrosss** [Abrosss/devquiz-quiz-app#6]
- [ ]  Gaps are increased and the page looks more balanced
<details>
<summary>Screenshot</summary>

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/84074575/59179086-2ae3-410f-aa2b-42252c717aff)

</details>

**Comment by rajsinghast03** [comment]
Hey! @Abrosss can i fix this?

**Comment by rajsinghast03** [comment]
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/104638199/1f445183-f6e2-46d1-b9c8-2cb1fa53e53b)
Did you like it? Suggest any changes if you want. If you found this good then can i make a PR?

**Comment by Abrosss** [comment]
Hi @rajsinghast03 ! Thank you for taking this issue! Could you please make the distance a little more even and maybe a little wider button like here on the picture. 
![Screenshot_34](https://github.com/Abrosss/devquiz-quiz-app/assets/84074575/56056e3e-5edc-4b1d-a8f0-7e043dd4c840)

**Comment by rajsinghast03** [comment]
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/104638199/f46c36f9-a2dc-42ae-9f8a-aaa70fbe47bb)
How about this one?

**Comment by Abrosss** [comment]
Hi @rajsinghast03. Yes this one, thank you. Please feel free to make a pull request!

**Comment by Abrosss** [comment]
#10 fixed this issue
