### ISSUE TITLE
The answer letter's div size does not occupy the answer's height

### ISSUE THREAD

**Issue by Abrosss** [Abrosss/devquiz-quiz-app#9]
- [ ] Fix CSS for the answer div, when the text size is big
<details>
<summary>Screenshot</summary>

![Screenshot_27](https://github.com/Abrosss/devquiz-quiz-app/assets/84074575/b1ac2bdb-2da9-440b-a161-c72a580b7070)

</details

**Comment by bansaltushar014** [comment]
Hi @Abrosss ,

I looked into the issue and I came up with different solutions of it. 

1. Lets give the width 100 percent to .answers_section then it will reduce the frequency of occurring our UI defects. Shown as below screenshots. 

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/d5e2a82e-3d19-4880-ac48-80d58712332e)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/aed0ae2b-ec33-41e6-87ed-e5f7c7d7e44d)

2. Increase the  size of icon .answers-section__letter and it will reduce the  occurring of this UI error to a great extent. As shown below in screenshots. 

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/e763482d-9b8c-44d9-a132-9886ee0c19f7)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/258546e5-632e-479d-94b3-a96a98d11832)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/4a955d02-a45c-45d9-9d05-df61c2adb8c7)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/ecedc56c-bd80-43b1-a114-9bd8536223a0)

3. We can also decrease the size of font of .answers-section__title  but that too will show UI error for bigger string as shown in screenshot. 

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/03c48fee-a177-4659-a5bb-7a451ad08530)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/208b3419-7bcc-48cf-996a-933cb2945b05)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/4533688e-289f-4196-a373-ff9e584a9a68)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/bbff2823-f328-47e5-8970-90b5ce9315f6)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/2b603449-2d7a-4f84-9a94-288d585a8533)

4. Remove the border at all. 

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/708b8ecb-f3c3-46a4-84a8-566bbb195294)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/5c57ded4-d39b-4a9c-914b-aca6592673cd)

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/2021e0ce-b2c2-488c-9a1b-a5ed8bbd7e98)
 
 I would like to know which suggestions seem acceptable to you?

**Comment by Abrosss** [comment]
Hi! Thank you so much @bansaltushar014  for taking time to work on this issue! I like the 4th option, but I think some borders are needed anyway, at least on hover or when the answer is selected (pic below), so will the problem remain if we don't delete borders on hover/selected. 
![Screenshot_30](https://github.com/Abrosss/devquiz-quiz-app/assets/84074575/e6875c70-ab94-4e0f-957e-655166b5ef4a)

**Comment by Abrosss** [comment]
@bansaltushar014 Yes, it looks better without the border
Also, both letter and the text are just spans now, without a container. What if we wrap the letter span in a div and then make the div fill the parent container (maybe wrap the text in a div too), what do you think?  I think it will make everything more responsive

**Comment by bansaltushar014** [comment]
I have perform with your suggestions where I have put condition of css on max-width 300px , 600px and above 600px. 

Now it is covering 90% of scenario but not 100 percent. Below are the screenshots. 

![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/9bc4faf1-264e-4c54-bcd7-04b4778302a1)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/82304d45-2f42-4fff-bd55-e0bdc58e7383)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/fd9ffe70-d1e9-451c-a86f-a2dc603c7224)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/f7da5d4b-7ee7-42f0-8f55-05552d69c390)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/db8afdb1-b2bf-41ed-9af2-0b39438a846f)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/fedfa550-9893-4420-81d4-890affe7a147)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/ed3af734-b43e-4070-8661-bcfaa0768601)
![image](https://github.com/Abrosss/devquiz-quiz-app/assets/51528049/b76ba64b-95ae-40fb-9181-feb165ea7d08)

I also had to decrease the font size as well in that condition.

**Comment by Abrosss** [comment]
Hi @bansaltushar014 oh I see! So you wrapped the letter and the text in containers? 
It's probably _align-items:center_ in the parent div causes it? Can you please remove it and check if it helps

**Comment by Abrosss** [comment]
Hi @bansaltushar014. I tried to remove align-items:center and it worked! Thank you for your time working on it. I closed the issue
